apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type : Opaque           #me type eka hami basic ma type eka thwa thiynwa types eka eka jathiye
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=