apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:                   # Defines how to find the pods that belong to this Deployment.
    matchLabels:
      app: mongodb
  template:                   #The template for the pods created by this Deployment.
    metadata:
      labels:
        app: mongodb
    spec:                     # Defines the specifications of the pod.
      containers:             #containers: A list of containers that run in each pod.
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongodb-secret
              key: mongo-root-password

---   #menna me line 3 theruma awilla document separation kiyna eka . ekiynne yaml wala apita puluwan document kipyaka eka file ekemliynna , ithin methanin pahalath thyan document eka already athulath wenwa   

#service: The Service exposes the MongoDB pod to the rest of the Kubernetes cluster, allowing other pods to access it.
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:                       #Defines the desired state of the Service.
  selector:               #Specifies the pods that the Service should expose.
    app: mongodb          #methna name eka kil denne pod eke name eka mona pod ektd me service ek thiynne wage ekk thami methn enne
  ports:
    - protocol: TCP
      port: 27017         #meka ser   vice port eka 
      targetPort: 27017   #meka containerPort of Deployment
#me ports kallata dlawa thiynne list ek listof ports, ekiynne dan me port eka list ekk mokd '-' symbol eka thiynwane , me list eke thiynne eka item kei , aaye list item ekk onnm '-' lakunen patna ganna wenwa 
      
#kubectl apply -f mongo.yaml
#deployment.apps/mongodb-deployment unchanged
#service/mongodb-service created an me service eka apply krddi me file ekami apply krnne kubectl ka hraha , ethkot enne menna me wage output ekk , service ek hadnea deployment ek unchanged